# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcrmapp', '0002_customer_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='avtar',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='avtar',
            new_name='avatar',
        ),
    ]
